[tool.poetry]
name = "most-similar-entity"
version = "0.1.0"
description = ""
authors = ["刘金晶 <liujinjing@cosla.cn>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
